# maize global configuration file example

# Where to save temporary files and all workflow directories
scratch = "/tmp/maize-scratch"

# Additional packages to load
#packages = [
#    "maize.steps.mai"
#]

packages = [
    "reinvent_plugins.components"
]
# here we are configuring the node defined as ``Example``:
[gnina]
python = "/home/corey/miniconda3/envs/maize/bin/python" # location of Python within Maize
commands.gnina = "/home/corey/local_software/gnina.1.3.2.cuda12.8" # Gnina executable location

#[vina]
# maize環境のPythonのPath, Vinaのインストールパスを指定して下さい
# example
#python = "/home/ubuntu/miniconda3/envs/maize/bin/python"
#commands.vina = "/opt/vina/bin/vina"

#[gypsum]
# gypsum environmentのインストールPath、実行用のスクリプトのPathを指定して下さい
# example
#scripts.gypsum.interpreter = "/Users/billtatsis/miniconda3/envs/gypsum/bin/python"
#scripts.gypsum.location = "/Users/billtatsis/pr0jects/C0d3_Doj0/mAiZe/CBI/gypsum_dl/run_gypsum_dl.py"

# Modules to load
#modules = ["program_module/1.0"]


# Scripts that require a specific interpreter
#scripts.program.interpreter = "path/to/python"
#scripts.program.location = "path/to/program/or/folder"

# Default parameter settings for this node
#parameters.value = 42
